[phases.setup]
nixPkgs = ["php82", "nodejs-18_x"] # نستخدم الأسماء التي يفهمها نظام Nix

[phases.build]
cmds = [
    "composer install --no-dev",
    "npm install",
    "npm run build",
    "php artisan optimize"
]

